int carregar();
void locar();
void entregar();
int buscacodigo();
int buscanome();
int buscaano();
int buscagenero();
int imprimir(int i);
int buscar();
void imprimirtudo();
void imprimirselecao();
void salvar(int i, FILE *arquivobackup);
int backup(int n);
int backup_ano(FILE *arquivobackup2);
int backup_genero(FILE *arquivobackup2);
int backupselect(int n);
